### ISSUE TITLE
incorrect yaml file for creating argo app

### ISSUE THREAD

**Issue by jesusmah** [ibm-cloud-architecture/refarch-kc-gitops#1]
I found that the appropriate yaml file to create an argoCD application should look like the following:
```
apiVersion: argoproj.io/v1alpha1
metadata:
  name: itgtests-kcontainer-order-command-ms
spec:
  destination:
    namespace: itgtests
    server: 'https://kubernetes.default.svc'
  source:
    path: ordercommandms
    repoURL: 'https://github.com/ibm-cloud-architecture/refarch-kc-gitops.git'
    targetRevision: itgtests/gse-eda-demos.us-east.containers.appdomain.cloud
    directory:
      recurse: true
      jsonnet: {}
  project: itgtests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```
which is a bit different from what we have in the readme as of now
